name: Build & test
on:
  push:
    branches: master
  pull_request:
    branches: master
env:
  CARGO_TERM_COLOR: always
jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v3
      - name: Setup Rust toolchain with caching
        uses: https://brndnmtthws/rust-action@v1
      - run: cargo check
        env:
          RUST_BACKTRACE: 1